server:
  port: 8080

spring:
  application:
    name: Ansible Docs Boot
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ansibledocsdb;Mode=MySQL
    username: ansible
    password: Ansible@1234
    platform: h2
    continue-on-error: true
    driver-class-name: org.h2.Driver
    hikari:
      initial-size: 1000
      max-idle: 1000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

awaitTermination: 120

hazelcast:
  health:
    monitoring:
      level: OFF

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE
    com.hazelcast.internal.diagnostics.HealthMonitor: off
  pattern:
    console: '[%p ] %d{yyyy-MM-dd HH:mm:ss,SSS} %M - %m%n'

logbook:
  filter:
    enabled: true
  write:
    level: INFO
  format:
    style: splunk
  exclude: [/, /actuator/**, /v3/api-docs/**, /swagger-ui/**, /index.html, /images/**, /swagger-ui.js, /lib/**, /css/**]
  strategy: body-only-if-status-at-least
  minimum-status: 400

MYSQL_DATABASE: ansible
MYSQL_USER: ansible
MYSQL_PASSWORD: Ansible@1234

# This directory has to be explicitly set to let Embedded MariaDB know the master persistence location.
# Use embedded/persistence/mariadb4j to have a common persistence location for all embedded components.
# Default is NONE
MARIADB4J_DIR: NONE

# If dataDir, libDir & baseDir are not set, then the database will not be persistent.
mariadb4j:
  dataDir: ${MARIADB4J_DIR}/data
  libDir: ${MARIADB4J_DIR}/lib
  baseDir: ${MARIADB4J_DIR}/base
  port: 3306
  maxConnections: 100000
  wait:
    timeout: 18000000
  connect:
    timeout: 31536000
  deleteBaseAndDataDirOnShutdown: true
  security:
    disabled: true
